Break _createDialog, _createInstance, _createForm into async steps
Neovici/cosmoz-dialog-old pull request #10
Opened 2017-11-03 16:09 UTC by megheaiulian

Break _createDialog, _createInstance,  _createForm into small async steps

2017-11-03 18:26 UTC, nomego approved these changes

2017-11-06 07:59 UTC, megheaiulian commented
Tests are hanging because of Polymer/web-component-tester#648. Will downgrade in `package.json` to `6.3.0`.

2017-11-06 09:41 UTC, plequang requested changes
In Polymer 1.x, all properties forwared in `_forwardParentProp` were forwared after the element was attached, so after the dialog template instance was created, and we wrere able to forward the properties to the template instance.
This is not the case anymore, so we should do the same as for Polymer 2.x, by storing these properties in `_pendingProps` and forward these after template instance creation

2017-11-07 09:03 UTC, plequang requested changes
See review comments.
There are also some eslint errors.

2017-11-07 09:03 UTC, plequang commented on cosmoz-dialog-behavior.html
> +			this._ensureTemplatized();
Don't know why, but `_ensureTemplatized` cannot be called during `created`.
When `templatize` is called during created, it seems Polymer does not find any properties to forward.
It works when `templatize` is called during `attached` though.

2017-11-07 09:03 UTC, plequang commented on cosmoz-dialog-behavior.html
> +				instance.forwardHostProp(key,props[key]);
In Polymer 1.x, this should be `instance[key] = ...`

2017-11-07 09:11 UTC, megheaiulian commented on cosmoz-dialog-behavior.html
> +				instance.forwardHostProp(key,props[key]);
Yes. `forwardHostProp` not available in 1.x

2017-11-07 09:14 UTC, megheaiulian commented on cosmoz-dialog-behavior.html
> +			this._ensureTemplatized();
@plequang To do this correctly we need first create a mutation observer and in it set `_userTemplate` to the first found template then continue to templatize and _createInstance and _createDialog.

2017-11-07 09:23 UTC, plequang commented on cosmoz-dialog-behavior.html
> +			this._ensureTemplatized();
OK

2017-11-07 11:50 UTC, plequang approved these changes

2017-11-07 11:50 UTC, merged